Mark Spawning.directions as optional
screepers/typed-screeps pull request #244
Opened 2023-08-11 16:20 UTC by tiennou

This property is only defined if it was passed as spawn options, or it got set through `Spawn.spawning.setDirections`. Otherwise it'll be `undefined` and the creep will default to `[TOP]`.

Fixes #243.

### Checklists

- [x] Test passed
- [x] Coding style (indentation, etc)
- [x] Edits have been made to `src/` files not `index.d.ts`
- [x] Run `npm run dtslint` to update `index.d.ts`

2023-08-12 09:09 UTC, DiamondMofeng commented
Thank you❤️. Anyway I think Typescript's `Optional Propertiy Modifier` `?:` is more suitable in this case.

```
interface A {
  p?: number;
}

let a: A = {} // OK
```

```
interface B {
  p: number | undefined | null
}

let b: B = {} // Error: Property 'p' is missing in type '{}' but required in type 'B'.
```

Although we won't create a `Spawning` object, the former case expresses better.

You can accept suggested changes on the website. Then we are ready to go🚀

2023-08-12 09:14 UTC, DiamondMofeng requested changes

2023-08-12 09:14 UTC, DiamondMofeng commented on src/spawn.ts
```suggestion
    directions?: DirectionConstant[];
```
use `?:` instead of `| undefined` to express optional property

2023-08-12 09:14 UTC, DiamondMofeng commented on dist/index.d.ts
To avoid recompilation

2023-08-12 09:23 UTC, DiamondMofeng requested changes

2023-08-12 09:23 UTC, DiamondMofeng commented on src/spawn.ts
use ?: instead of | undefined to express optional property

2023-08-12 09:29 UTC, DiamondMofeng requested changes

2023-08-12 09:29 UTC, DiamondMofeng commented on dist/index.d.ts
> +    directions: DirectionConstant[] | undefined;
```suggestion
    directions?: DirectionConstant[];
```
To avoid re-building

2023-08-12 09:29 UTC, DiamondMofeng commented on src/spawn.ts
> +    directions: DirectionConstant[] | undefined;
```suggestion
    directions?: DirectionConstant[];
```
we use `?:` instead of `| undefined` to express an optional property

2023-08-16 13:28 UTC, tiennou commented
There you go!

2023-08-16 15:24 UTC, DiamondMofeng approved these changes
LGTM

2023-08-16 15:24 UTC, merged